travis:
  secure:
    BINSTAR_TOKEN: XfULSD5ZO25/ZPnJvJHHQ0/QZx5k2v0HtYZvX0vTK50mNzgBWBRns9oHZslTENh3XGwBIR5bg0Vg0KP9pZ3fDfpb32hHhBXnehgUk/yTP0IjErYMx06atf0gACKL1wTkn/GLE6k1U01M0Ljd4BKu3JEAZBF6Id5ga5aYfP837P0bEJ8DA0079yvQwAqxtqVNM9oaiAG5jq1aDVNpstL6WqEJsA/tf6Ylfz/lqigjkQSPZcuPJQA0/Mw6zfKPovgzEb33SIc/dW9pIuSfzLLQi+CS92nitl2DrbztY1bZGgDkrPSZqAXJQw8RkXnZBmsjRdwsfFuEMdI3/7QGcjb7vH50tV1C7r6/3Hz2R/ESxQoc/Z6ZrIQGK3UUuMCcM11/nmRdJjtOE54IGVfNKEdqi/tEDOY3bchs21698B8XnzZeyrGRz3Oy8qxPYBf+1F+Ua7uhPxAuMkA5yI3o2QjNtko5vKY9wspB2Gz2fCCbFHp7lh4hGwkKgbQEdYXG7f32gvFLQkkYHwk+9zBSO5luocKFKJtmGD47ZbVkp+mRbJTjlLWBHJ24DyUYAje9esT0TqGQACly/6nMdOmFz8FFmlvIIdtKF9y1w1r42u5/q0XXVv0/oBUh1tejxaYOIwUcUkzme8BCMQFZIliIWW8U6mP+TobdQJIxDpHwqBmJFfo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
